FROM mcr.microsoft.com/devcontainers/rust:1-bookworm

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        ca-certificates \
        imagemagick \
        jq \
        libreoffice \
        make \
        poppler-utils \
        tesseract-ocr \
        tesseract-ocr-eng \
        tesseract-ocr-jpn \
        unzip \
    && rm -rf /var/lib/apt/lists/* \
    && cargo install just --locked
